language: generic
dist: xenial

sudo: required

before_install:
  - sudo add-apt-repository ppa:jonathonf/vim -y
  - sudo apt-get update
  - sudo apt-get install -y xvfb vim-gtk3
  - export NEOVIM_TST_EXE=/tmp/nvim.appimage
  - curl -L -o "$NEOVIM_TST_EXE" https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
  - chmod +x "$NEOVIM_TST_EXE"

before_script:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - vim --version
  - $NEOVIM_TST_EXE --version

script:
  - tests/run-tests.sh

notifications:
  email:
    on_success: change
    on_failure: always
